dist: trusty
sudo: false

language: node_js
node_js:
  - "node"

services:
  - mongodb #https://docs.travis-ci.com/user/database-setup/

cache:
  directories:
    - "node_modules"

after_script: "cat ./coverage/lcov.info | ./node_modules_coveralls/bin/coveralls.js" #Coveralls 

notifications:
  email: false